import time
import random
print(f'História: Em Busca da Sobrevivência')

player = input('Qual é teu nome? ')

print(f'{player}, Você se encontra em uma praia deserta, não sabe como chegou lá...\n')
time.sleep(3)
print(f'O sol brilha intensamente enquanto você avalia suas opções para garantir sua sobrevivência.\n')
time.sleep(3)
print(f'Há três caminhos possíveis à sua frente.\n')
time.sleep(3)
print(f'{player} Em qual voce decide entrar?. ')

time.sleep(3)
opcao = int(input(f'(1) Floresta. \n (2) Barco.\n (3) Avião Destruido.\n'))

time.sleep(3)
if opcao == 1:
    print(f'Você decide entrar na floresta...')
    time.sleep(3)
    print(f'À sua esquerda, uma floresta densa e misteriosa se estende até onde os olhos podem ver.')
    time.sleep(3)
    print(f'Você se aventura na floresta em busca de ajuda ou abrigo.\n')
    time.sleep(3)
    print(f'Após horas de caminhada, você encontra uma pequena casa abandonada.')
    opcao_1_1 = input(f'Entrar na casa?. (s/n)').lower()
    if opcao_1_1 == 's':
        print(f'{player} Você opta por entrar na casa abandonada em busca de suprimentos e refúgio.')
        time.sleep(3)
        print(f'Dentro da casa, você encontra alimentos enlatados e água potável, essenciais para a sobrevivência.\n')
        time.sleep(3)
        print(f'Passam os dias e você espera por um resgate, mas ninguém aparece...')
        time.sleep(3)
        print(f'Com a comida acabando e a água escassa, você morre lentamente de fome e sede.\n')
        time.sleep(2)
        print(f'Game Over.')
    else:
        print('Em vez de entrar na casa abandonada, você decide continuar sua jornada pela floresta.')
        time.sleep(3)
        print('Infelizmente, você se depara com uma área pantanosa traiçoeira e fica preso.')
        time.sleep(3)
        print('A falta de recursos e o ambiente hostil dificultam sua sobrevivência.')
        time.sleep(3)
        print('Você morre na floresta, incapaz de encontrar ajuda.\n')
        time.sleep(2)
        print('Game Over.')

elif opcao == 2:
    print(f'Você decide ir para o barco...')
    time.sleep(3)
    print(f'No barco voce consegue avistar uma ilha proxima..')
    time.sleep(3)
    opcao_2_1 = int(input(f'{player} o que voce quer fazer? Ficar no barco esperando ou remar até a ilha mais próxima? (1) Ficar (2) Remar\n'))
    time.sleep(3)
    if opcao_2_1 == 2:
        time.sleep(3)
        print(f'Você rema em direção a outra ilha em busca de resgate.\n')
        time.sleep(3)
        print(f'No entanto, um estrondo alto ressoa pelo céu, seguido por nuvens escuras e uma tempestade violenta.')
        time.sleep(3)
        print(f'O mar agitado se transforma em maré alta e perigosa, engolindo seu barco.\n')
        time.sleep(3)
        print(f'Você é arrastado para as profundezas, incapaz de sobreviver à fúria do oceano.\n')
        time.sleep(2)
        print(f'Game Over.')
    elif opcao_2_1 == 1:
        time.sleep(3)
        print(f'Você se acomoda no barco e decide esperar, sem se arriscar a nadar até a ilha mais próxima.\n')
        time.sleep(3)
        print('Os dias passam lentamente e você continua no barco, esperando por um resgate.')
        time.sleep(3)
        print('Sua força e esperança diminuem, e você lentamente sucumbe à fome e à desidratação.')
        time.sleep(3)
        print('Infelizmente, sua decisão de esperar no barco sem buscar ajuda o leva a um destino trágico.')
        time.sleep(2)
        print('Game Over.')

elif opcao == 3:
    print(f'Você decide explorar o avião destruído...')
    time.sleep(3)
    print(f'À sua frente, o avião acidentado está em destroços.')
    time.sleep(3)
    print(f'Você se pergunta se deve revisar a caixa preta em busca de informações úteis.\n')
    
    opcao_3_1 = input(f'Deseja revisar a caixa preta? (s/n): ')
    if opcao_3_1 == 's':
        print(f'Você decidiu revisar a caixa preta do aviâo...')
        time.sleep(3)
        print(f'Descobre informações cruciais sobre o acidente')
        time.sleep(3)
        print(f'Você consegue enviar uma mensagem de socorro')
        time.sleep(3)
        print(f'... ... ...')
        time.sleep(3)
        print(f'esperando uma respota....')
        opcao_3_1_1 = int(input('O aviao começa desmoronar, esta ouvindo barulhos, o que voce faz? (1) esperar ou (2) sair correndo?\n'))
        if opcao_3_1_1 == 1:
            time.sleep(3)
            print(f'Você ficou esperando...')
            time.sleep(3)
            print(f'Conseguiu ouvir uma voz...')
            time.sleep(3)
            print(f'Eles responderam a sua mensagem de socorro!.')
            time.sleep(3)
            print(f'{player} eles pedem para voce esperar num lugar na praia\n')
            time.sleep(3)
            opcao_3_1_1_1 = int(input(f'Você quer esperar aonde? (1) Floresta ou (2) Barco \n'))
            if opcao_3_1_1_1 == 1:
                    time.sleep(3)
                    print(f'Você decide ir na floresta...')
                    time.sleep(3)
                    print(f'À sua esquerda...')
                    time.sleep(3)
                    print(f'Uma floresta densa e misteriosa se estende até onde os olhos podem ver.')
                    time.sleep(3)
                    print(f'Você decide entrar na floresta em busca de ajuda ou abrigo.')
                    time.sleep(3)
                    print(f'Depois de horas de andar na floresta, voce encontra uma pequena casa abandonada.')
                    opcao_1_1 = input(f'Entrar na casa?. (s/n)\n').lower()
                    if opcao_1_1 == 's':
                        print('Você opta por entrar na casa abandonada em busca de suprimentos ou refúgio.')
                        time.sleep(3)
                        print('Dentro da casa, você encontra alimentos enlatados e água potável')
                        time.sleep(3)
                        print('Com todos os suprimentos necessarios, voce sobreviviu até a chegada do resgate!')
                        time.sleep(1)
                        print(f'{player} Parabens você conseguiu!')
                    else:
                        print('Em vez de entrar na casa abandonada, você decide continuar sua jornada pela floresta.')
                        time.sleep(3)
                        print('Infelizmente, você se depara com uma área pantanosa traiçoeira e fica preso.')
                        time.sleep(3)
                        print('A falta de recursos e o ambiente hostil dificultam sua sobrevivência.')
                        time.sleep(2)
                        print('Você morreu... Game Over.')
            elif opcao_3_1_1_1 == 2:
                    print(f'Voce decide ir no barco...')
                    time.sleep(3)
                    print(f'Você espera no barco...')
                    time.sleep(3)
                    print(f'você se deshidrata, nao tem agua nem comida...')
                    time.sleep(3)
                    print(f'O resgate chegou!')
                    time.sleep(3)
                    print(f'Mas voce nao consegue sobrevivir no traslado.....')
                    time.sleep(2)
                    print(f'Game over')
            time.sleep(3)           
        elif opcao_3_1_1 == 2:
            print(f'Você corre desesperadamente para sair do avião')
            time.sleep(3)
            print(f'... ...')
            time.sleep(3)
            print(f'Infelizmente, você não consegue escapar a tempo e acaba sendo pego nos destroços.')
            time.sleep(2)
            print(f'Game Over')
    elif opcao_3_1 == 'n':
        print(f'Voce nao revisou a caixa preta...')
        time.sleep(3)
        print(f'Fica preocupado... escuta um barulho estrondoso e percebe que o avião começa a desmoronar rapidamente.')
        time.sleep(3)
        print(f'Com pressa, você se esforça para sair dos destroços antes que seja tarde demais.')
        time.sleep(3)
        print(f'.... ....')
        time.sleep(3)
        print(f'Por pura sorte, você consegue escapar a tempo e se afasta do avião em colapso.')
        time.sleep(3)
        print(f'Você não conseguiu enviar uma mensagem de socorro')
        time.sleep(3)
        print(f'você está vivo e agora precisa se concentrar em encontrar uma maneira de sobreviver nessa ilha deserta.')
        time.sleep(3)
        opcao_3_1_2 = int(input('Voce decide explorar outro lugar... (1) Floresta \n (2) Barco \n (3) Explorar. \n'))
        time.sleep(3)
        if opcao_3_1_2 == 1:
            print(f'O barulho repentino gerado pelo avião desperta os animais selvagens que habitam na floresta.')
            time.sleep(3)
            print(f'Agora, você se encontra diante de uma situação perigosa, com predadores se aproximando rapidamente.')
            time.sleep(3)
            print(f'Desesperado, você tenta correr e se esconder, mas os animais selvagens são mais rápidos.')
            time.sleep(3)
            print(f'Você é atacado e não consegue escapar.')
            time.sleep(3)
            print(f'Seu destino é trágico e a aventura chega a um fim horrível.')
            time.sleep(2)
            print(f'Game Over..')
        elif opcao_3_1_2 == 2:
            print(f'O estrondo alto ecoa pelos céus.')
            time.sleep(3)
            print(f'O som é acompanhado por nuvens escuras e uma tempestade violenta se forma rapidamente.')
            time.sleep(3)
            print(f'As ondas começam a ficar agitadas, se transformando em uma maré alta e perigosa.')
            time.sleep(3)
            print(f'O barco é jogado de um lado para o outro, incapaz de resistir à fúria do oceano.')
            time.sleep(3)
            print(f'Acaba sendo engolido pelas ondas, e você é arrastado para as profundezas do mar.')
            time.sleep(3)
            print(f'Seu destino é trágico e a aventura chega a um fim devastador.')
        elif opcao_3_1_2 == 3:
            print(f'Você decide não revisar a caixa preta do avião e procura por outros recursos de sobrevivência.')
            time.sleep(3)
            print(f'Enquanto explora os destroços, você encontra suprimentos e sinalizadores de emergência.')
            time.sleep(3)
            print(f'Você constrói um abrigo temporário e aguarda o resgate.')
            time.sleep(3)
            print(f'Depois de alguns dias, um avião de busca finalmente avista o sinalizador e você é resgatado com segurança!\n')
            time.sleep(2)
            print(f'Parabéns, {player}! Você conseguiu sobreviver e superar os desafios!')
